### ISSUE TITLE
It should set IP on first run

### ISSUE THREAD

**Issue by Nixellion** [nikhiljohn10/ddns-on-cloudflare#1]
Great script, but I think there's one huge flaw in it that makes it unusable in any real scenario. Or in a lot of them at least. I've tweaked it for myself, but here it is:

Right now it seems to not change IP when it's first launches. I believe this is wrong. 

Imagine this scenario:
I've set everything up at home (say, video surveilance system on raspberry pi), and then unplugged everything and moved it to another location. I plug it back in and naturally I will get assigned a new IP. But ddns script will not change it until the NEXT change. So it can stay on that IP for as long as.... well maybe until it reboots even, depending on how long lease time for IP is.

Fix is simple. Don't run `self.get_ip()` on `__init__`. 

```
class DDNS(object):
	def __init__(self,secret_path):
		super(DDNS, self).__init__()
		zone_name, email, token, certtoken = secrets.get(secret_path)
		self.zone_name = zone_name
		self.ip='0.0.0.0'
		self.dns = CloudFlare.CloudFlare(email = email, token = token, certtoken = certtoken)
		#self.get_ip() # Comment this line out
		self.get_zone_id()
		self.get_record_id()
		self.update_dns()
		self.worker()
```

Another option would be to write IP to disk, not just keeping it in RAM. This way even after reboot it will be able to check if IP changed or not.

**Comment by nikhiljohn10** [comment]
Hi @Nixellion ,

I am sorry. I could not quite get why it won't update when you move to next location. This compiled python file will be executed every time you turn on/ reboot the system. Thus the `__init__` method is called as well. So as this happens, it retrieve the public ip and update `self.ip` if it is any different than `self.old_ip`. This is continued every 60 seconds. So no matter what, it updates new ip to server if it is not matching old ip. ALso note that `self.old_ip` is initialised inside **worker( )** method. I hope this solves your doubt. But if you have something better, feel free to send away a pull request. I'll look in to it.

Cheers,

Nikz

**Comment by Nixellion** [comment]
Yeah, now that I looked at it again I'm not sure why it did not work and started working when I commended that line out, huh.

Sorry to bother.

**Comment by nikhiljohn10** [comment]
No problem. Glad to clear you doubt. I am trying to optimize and expand the features and compatibility. If you are interested to contribute, check out dev-init branch. I am trying to add more types of init processes compatibility.
