### ISSUE TITLE
[QUESTION] What is the point of compiling it with pyinstaller

### ISSUE THREAD

**Issue by Nixellion** [nikhiljohn10/ddns-on-cloudflare#2]
Is there any significant performance improvement or what other improvements does it get from being compiled with pyinstaller? Why not just let it run with python? 

Or is it just to not pollute environment with libraries?

**Comment by nikhiljohn10** [comment]
Hi @Nixellion,

It create a single binary file to execute for the cpu. As it is compiled, the code execute fast and solid. pyinstaller is a cross platform compiler. So for example, if you compile it in windows or linux, you dont need to worry much. The binary file work same in almost all OS of similar kernel like windows exe file works is windows 7,8,8.1,10 etc in same way.

This is not just it, i have not yet completed it. I am continuing next part of it in a different branch and merge it one its stable.
