### ISSUE TITLE
Unable to find Cloudflare User-Service-Key

### ISSUE THREAD

**Issue by pheistman** [nikhiljohn10/ddns-on-cloudflare#3]
Hi,
I wish to use your script to automate updating my ddns on Cloudflare but I keep getting the log messages below because I think I dont have the Cloudflare user service key.
Is this key still provided by cloudflare as I can only see my Global API and Origin CA keys under my dashboard? Is there a workaround if this key is no longer provided by cloudflare?

./setup.sh: line 19: pip: command not found
./setup.sh: line 20: pip: command not found
./setup.sh: line 21: pip: command not found
./setup.sh: line 36: pyinstaller: command not found
cp: cannot stat './dist/main': No such file or directory
Setting up systemd service
cp: cannot stat 'ddns': No such file or directory
Created symlink from /etc/systemd/system/multi-user.target.wants/ddns.service to /lib/systemd/system/ddns.service.
./setup.sh: line 69: pip: command not found
Setup completed successfully
● ddns.service - DDNS on Cloudflare
   Loaded: loaded (/lib/systemd/system/ddns.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-02-20 21:08:25 GMT; 14ms ago
  Process: 19877 ExecStart=/usr/sbin/ddns /opt/ddns-on-cloudflare (code=exited, status=203/EXEC)
 Main PID: 19877 (code=exited, status=203/EXEC)

Feb 20 21:08:25 nathan systemd[1]: ddns.service: Unit entered failed state.
Feb 20 21:08:25 nathan systemd[1]: ddns.service: Failed with result 'exit-code'.

**Comment by kamilmirza** [comment]
@pheistman 
looks like you don't have `pip` installed
install `pip` and try again

**Comment by pheistman** [comment]
Thanks for the response, i'll try it out

**Comment by kamilmirza** [comment]
@pheistman 
i apologize for my previous comment
it's called Origin Key, right below your API Key
starts with `v1...`

**Comment by pheistman** [comment]
Thanks a lot for your assistance. I've installed pip and used the Origin Key which has got it working.
However, I've noticed that after the script creates an A Record of **ddns** in Cloudflare which points to my updated IP address, I now have 2 A records.
The first is **ddns** A record which points to the updated IP address and the second A record is my domain name pointing to my old IP address.
Is there a way to keep 1 A record which gets updated when the script runs? 

Thanks in advance

**Comment by kamilmirza** [comment]
> Is there a way to keep 1 A record which gets updated when the script runs?

have you tried removing the second A record?
happens when you remove it?

**Comment by pheistman** [comment]
Ok so 2 things happen.
1. When i remove the newly created ddns A record, I still have my old A record which is my domain name pointing to the old IP address. After running the script, it only creates a new A record with name ddns which points to the updated IP address.

2. When i remove the A record which has the name of my domain pointing to the old IP address, all i have left is the newly created ddns A record pointing to the updated IP address. It breaks my website making it unreachable. Cloudflare also puts up a warning that "An A, AAAA or CNAME record was not found pointing to the root domain. The domain will not resolve."

**Comment by nikhiljohn10** [comment]
> 
> 
> Thanks a lot for your assistance. I've installed pip and used the Origin Key which has got it working.
> However, I've noticed that after the script creates an A Record of **ddns** in Cloudflare which points to my updated IP address, I now have 2 A records.
> The first is **ddns** A record which points to the updated IP address and the second A record is my domain name pointing to my old IP address.
> Is there a way to keep 1 A record which gets updated when the script runs?
> 
> Thanks in advance

Hi @pheistman, Sorry for the late reply. Idk if you figured it out. I understand the 2 A Records are `example.com` and `ddns.example.com`. These are not the same A Records. Your root domain is having your old IP and the program is set to create an sub domain to track your ddns ip. 

You have 2 option:

1. Reprogram the source code to take root domain instead of sub domain.
2. Use your root domain for some other purpose like hosting something in git and use ddns sub domain for accessing your local ip.

**Comment by pheistman** [comment]
Thanks Nik, however, since I couldnt get it working i found another script which is currently functioning the way i want it to. Thanks again.
